spring.application.name=guinacarautomotive
server.port=8081

# Conexão com o PostgreSQL (porta padrão 5432)
spring.datasource.url=jdbc:postgresql://localhost:5432/guinacarautomotive
spring.datasource.username=postgres
spring.datasource.password=root

# Configurações do Hibernate (cria as tabelas automaticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# ==========================================
# CONFIGURAÇÕES DE E-MAIL (GMAIL)
# ==========================================
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=leonardocaetanocosta2005@gmail.com
#spring.mail.password=dbug vbkj vied nzkd
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
